isced_formats_fr_fr <- c(
    '{{isced_broad_field}}',
    '{{isced_narrow_field}}',
    '{{isced_detailed_field}}'
)

isced_broad_field_fr_fr <- c('Programmes et certifications g\xe9n\xe9riques',
                             '\xc9ducation',
                             'Lettres et arts',
                             'Sciences sociales, journalisme et information',
                             'Commerce, administration et droit',
                             'Sciences naturelles, math\xe9matiques et statistiques',
                             'Technologies de l&#x2019;information et de la communication',
                             'Ing\xe9nierie, industries de transformation et construction',
                             'Agriculture, sylviculture, halieutique et sciences v\xe9t\xe9rinaires',
                             'Sant\xe9 et protection sociale',
                             'Services')

isced_narrow_field_fr_fr <- c('Programmes et certifications de base',
                              'Alphab\xe9tisation et apprentissage du calcul',
                              'Comp\xe9tences et d\xe9veloppement personnels',
                              '\xc9ducation',
                              'Arts',
                              'Lettres (\xe0 l&#x2019;exception des langues)',
                              'Langues',
                              'Sciences sociales et du comportement',
                              'Journalisme et information',
                              'Commerce et administration',
                              'Droit',
                              'Sciences biologiques et apparent\xe9es',
                              'Environnement',
                              'Sciences physiques',
                              'Math\xe9matiques et statistiques',
                              'Technologies de l&#x2019;information et de la communication',
                              'Ing\xe9nierie et techniques apparent\xe9es',
                              'Industries de transformation et de traitement',
                              'Architecture et b\xe2timent',
                              'Agriculture',
                              'Sylviculture',
                              'Halieutique',
                              'Sciences v\xe9t\xe9rinaires',
                              'Sant\xe9',
                              'Protection sociale',
                              'Services aux particuliers',
                              'Services d&#x2019;hygi\xe8ne et de sant\xe9 au travail',
                              'Services de s\xfbret\xe9',
                              'Services de transport')

isced_detailed_field_fr_fr <- c('Programmes et certifications de base',
                                'Alphab\xe9tisation et apprentissage du calcul',
                                'Comp\xe9tences et d\xe9veloppement personnels',
                                'Sciences de l&#x2019;\xe9ducation',
                                'Formation des enseignants au niveau pr\xe9scolaire',
                                'Formation des enseignants (sans sp\xe9cialisation)',
                                'Formation des enseignants (avec sp\xe9cialisation)',
                                'Techniques audiovisuelles et production multim\xe9dia',
                                'Stylisme, d\xe9coration et design industriel',
                                'Beaux-arts',
                                'Artisanat',
                                'Musique, th\xe9\xe2tre, danse, cirque',
                                'Religion et th\xe9ologie',
                                'Histoire et arch\xe9ologie',
                                'Philosophie et morale',
                                'Acquisition d&#x2019;une langue',
                                'Litt\xe9rature et linguistique',
                                '\xc9conomie',
                                'Sciences politiques et \xe9ducation civique',
                                'Psychologie',
                                'Sociologie et \xe9tudes culturelles',
                                'Journalisme et reportage',
                                'Formation aux biblioth\xe8ques, \xe0 la documentation et \xe0 l&#x2019;archivisme',
                                'Comptabilit\xe9 et fiscalit\xe9',
                                'Finance, banque et assurances',
                                'Gestion et administration',
                                'Marketing et publicit\xe9',
                                'Travail de secr\xe9tariat et de bureau',
                                'Vente en gros et au d\xe9tail',
                                'Comp\xe9tences professionnelles',
                                'Droit',
                                'Biologie',
                                'Biochimie',
                                'Sciences environnementales',
                                'Environnements naturels et faune et flore',
                                'Chimie',
                                'Sciences de la Terre',
                                'Physique',
                                'Math\xe9matiques',
                                'Statistiques',
                                'Utilisation d&#x2019;un ordinateur',
                                'Conception et administration de bases de donn\xe9es et de r\xe9seau',
                                'D\xe9veloppement et analyse de logiciels et d&#x2019;applications',
                                'Ing\xe9nierie chimique et processus',
                                'Technologie de la protection de l&#x2019;environnement',
                                '\xc9lectricit\xe9 et \xe9nergie',
                                '\xc9lectronique et automatisation',
                                'M\xe9canique et travail du m\xe9tal',
                                'V\xe9hicules \xe0 moteur, bateaux et a\xe9ronefs',
                                'Traitement des aliments',
                                'Mat\xe9riaux (verre, papier, plastique et bois)',
                                'Textiles (v\xeatements, chaussures et cuir)',
                                'Exploitation mini\xe8re et extraction',
                                'Architecture et urbanisme',
                                'B\xe2timent et g\xe9nie civil',
                                'Culture et \xe9levage',
                                'Horticulture',
                                'Sylviculture',
                                'P\xeacheries',
                                'Sciences v\xe9t\xe9rinaires',
                                '\xc9tudes dentaires',
                                'M\xe9decine',
                                'Soins infirmiers et formation de sages-femmes',
                                'Technologie m\xe9dicale diagnostique et de traitement',
                                'Th\xe9rapie et r\xe9\xe9ducation',
                                'Pharmacie',
                                'M\xe9decine et th\xe9rapie traditionnelles et compl\xe9mentaires',
                                'Soins aux personnes \xe2g\xe9es et aux adultes handicap\xe9s',
                                'Soins aux enfants et services pour la jeunesse',
                                'Travail social et accompagnement',
                                'Services \xe0 domicile',
                                'Coiffure et soins de beaut\xe9',
                                'H\xf4tellerie et services de restauration',
                                'Sports',
                                'Voyage, tourisme et loisirs',
                                'Salubrit\xe9 publique',
                                'Sant\xe9 et s\xe9curit\xe9 du travail',
                                'Arm\xe9e et d\xe9fense',
                                'Protection des personnes et des biens',
                                'Services de transport')
