isced_formats_en_us <- c(
    '{{isced_broad_field}}',
    '{{isced_narrow_field}}',
    '{{isced_detailed_field}}'
)

isced_broad_field_en_us <- c('Generic programmes and qualifications',
                             'Education',
                             'Arts and humanities',
                             'Social sciences, journalism and information',
                             'Business, administration and law',
                             'Natural sciences, mathematics and statistics',
                             'Information and Communication Technologies',
                             'Engineering, manufacturing and construction',
                             'Agriculture, forestry, fisheries and veterinary',
                             'Health and welfare',
                             'Services')

isced_narrow_field_en_us <- c('Basic programmes and qualifications',
                              'Literacy and numeracy',
                              'Personal skills and development',
                              'Education',
                              'Arts',
                              'Humanities (except languages)',
                              'Languages',
                              'Social and behavioural sciences',
                              'Journalism and information',
                              'Business and administration',
                              'Law',
                              'Biological and related sciences',
                              'Environment',
                              'Physical sciences',
                              'Mathematics and statistics',
                              'Information and Communication Technologies',
                              'Engineering and engineering trades',
                              'Manufacturing and processing',
                              'Architecture and construction',
                              'Agriculture',
                              'Forestry',
                              'Fisheries',
                              'Veterinary',
                              'Health',
                              'Welfare',
                              'Personal services',
                              'Hygiene and occupational health services',
                              'Security services',
                              'Transport services')

isced_detailed_field_en_us <- c('Basic programmes and qualifications',
                                'Literacy and numeracy',
                                'Personal skills and development',
                                'Education science',
                                'Training for pre-school teachers',
                                'Teacher training without subject specialisation',
                                'Teacher training with subject specialisation',
                                'Audio-visual techniques and media production',
                                'Fashion, interior and industrial design',
                                'Fine arts',
                                'Handicrafts',
                                'Music and performing arts',
                                'Religion and theology',
                                'History and archaeology',
                                'Philosophy and ethics',
                                'Language acquisition',
                                'Literature and linguistics',
                                'Economics',
                                'Political sciences and civics',
                                'Psychology',
                                'Sociology and cultural studies',
                                'Journalism and reporting',
                                'Library, information and archival studies',
                                'Accounting and taxation',
                                'Finance, banking and insurance',
                                'Management and administration',
                                'Marketing and advertising',
                                'Secretarial and office work',
                                'Wholesale and retail sales',
                                'Work skills',
                                'Law',
                                'Biology',
                                'Biochemistry',
                                'Environmental sciences',
                                'Natural environments and wildlife',
                                'Chemistry',
                                'Earth sciences',
                                'Physics',
                                'Mathematics',
                                'Statistics',
                                'Computer use',
                                'Database and network design and administration',
                                'Software and applications development and analysis',
                                'Chemical engineering and processes',
                                'Environmental protection technology',
                                'Electricity and energy',
                                'Electronics and automation',
                                'Mechanics and metal trades',
                                'Motor vehicles, ships and aircraft',
                                'Food processing',
                                'Materials (glass, paper, plastic and wood)',
                                'Textiles (clothes, footwear and leather)',
                                'Mining and extraction',
                                'Architecture and town planning',
                                'Building and civil engineering',
                                'Crop and livestock production',
                                'Horticulture',
                                'Forestry',
                                'Fisheries',
                                'Veterinary',
                                'Dental studies',
                                'Medicine',
                                'Nursing and midwifery',
                                'Medical diagnostic and treatment technology',
                                'Therapy and rehabilitation',
                                'Pharmacy',
                                'Traditional and complementary medicine and therapy',
                                'Care of the elderly and of disabled adults',
                                'Child care and youth services',
                                'Social work and counselling',
                                'Domestic services',
                                'Hair and beauty services',
                                'Hotel, restaurants and catering',
                                'Sports',
                                'Travel, tourism and leisure',
                                'Community sanitation',
                                'Occupational health and safety',
                                'Military and defence',
                                'Protection of persons and property',
                                'Transport services')

