isced_formats_fr_fr <- c(
    '{{isced_broad_field}}',
    '{{isced_narrow_field}}',
    '{{isced_detailed_field}}'
)

isced_broad_field_fr_fr <- c('Programmes et certifications génériques',
                             'Éducation',
                             'Lettres et arts',
                             'Sciences sociales, journalisme et information',
                             'Commerce, administration et droit',
                             'Sciences naturelles, mathématiques et statistiques',
                             'Technologies de l’information et de la communication',
                             'Ingénierie, industries de transformation et construction',
                             'Agriculture, sylviculture, halieutique et sciences vétérinaires',
                             'Santé et protection sociale',
                             'Services')

isced_narrow_field_fr_fr <- c('Programmes et certifications de base',
                              'Alphabétisation et apprentissage du calcul',
                              'Compétences et développement personnels',
                              'Éducation',
                              'Arts',
                              'Lettres (à l’exception des langues)',
                              'Langues',
                              'Sciences sociales et du comportement',
                              'Journalisme et information',
                              'Commerce et administration',
                              'Droit',
                              'Sciences biologiques et apparentées',
                              'Environnement',
                              'Sciences physiques',
                              'Mathématiques et statistiques',
                              'Technologies de l’information et de la communication',
                              'Ingénierie et techniques apparentées',
                              'Industries de transformation et de traitement',
                              'Architecture et bâtiment',
                              'Agriculture',
                              'Sylviculture',
                              'Halieutique',
                              'Sciences vétérinaires',
                              'Santé',
                              'Protection sociale',
                              'Services aux particuliers',
                              'Services d’hygiène et de santé au travail',
                              'Services de sûreté',
                              'Services de transport')

isced_detailed_field_fr_fr <- c('Programmes et certifications de base',
                                'Alphabétisation et apprentissage du calcul',
                                'Compétences et développement personnels',
                                'Sciences de l’éducation',
                                'Formation des enseignants au niveau préscolaire',
                                'Formation des enseignants (sans spécialisation)',
                                'Formation des enseignants (avec spécialisation)',
                                'Techniques audiovisuelles et production multimédia',
                                'Stylisme, décoration et design industriel',
                                'Beaux-arts',
                                'Artisanat',
                                'Musique, théâtre, danse, cirque',
                                'Religion et théologie',
                                'Histoire et archéologie',
                                'Philosophie et morale',
                                'Acquisition d’une langue',
                                'Littérature et linguistique',
                                'Économie',
                                'Sciences politiques et éducation civique',
                                'Psychologie',
                                'Sociologie et études culturelles',
                                'Journalisme et reportage',
                                'Formation aux bibliothèques, à la documentation et à l’archivisme',
                                'Comptabilité et fiscalité',
                                'Finance, banque et assurances',
                                'Gestion et administration',
                                'Marketing et publicité',
                                'Travail de secrétariat et de bureau',
                                'Vente en gros et au détail',
                                'Compétences professionnelles',
                                'Droit',
                                'Biologie',
                                'Biochimie',
                                'Sciences environnementales',
                                'Environnements naturels et faune et flore',
                                'Chimie',
                                'Sciences de la Terre',
                                'Physique',
                                'Mathématiques',
                                'Statistiques',
                                'Utilisation d’un ordinateur',
                                'Conception et administration de bases de données et de réseau',
                                'Développement et analyse de logiciels et d’applications',
                                'Ingénierie chimique et processus',
                                'Technologie de la protection de l’environnement',
                                'Électricité et énergie',
                                'Électronique et automatisation',
                                'Mécanique et travail du métal',
                                'Véhicules à moteur, bateaux et aéronefs',
                                'Traitement des aliments',
                                'Matériaux (verre, papier, plastique et bois)',
                                'Textiles (vêtements, chaussures et cuir)',
                                'Exploitation minière et extraction',
                                'Architecture et urbanisme',
                                'Bâtiment et génie civil',
                                'Culture et élevage',
                                'Horticulture',
                                'Sylviculture',
                                'Pêcheries',
                                'Sciences vétérinaires',
                                'Études dentaires',
                                'Médecine',
                                'Soins infirmiers et formation de sages-femmes',
                                'Technologie médicale diagnostique et de traitement',
                                'Thérapie et rééducation',
                                'Pharmacie',
                                'Médecine et thérapie traditionnelles et complémentaires',
                                'Soins aux personnes âgées et aux adultes handicapés',
                                'Soins aux enfants et services pour la jeunesse',
                                'Travail social et accompagnement',
                                'Services à domicile',
                                'Coiffure et soins de beauté',
                                'Hôtellerie et services de restauration',
                                'Sports',
                                'Voyage, tourisme et loisirs',
                                'Salubrité publique',
                                'Santé et sécurité du travail',
                                'Armée et défense',
                                'Protection des personnes et des biens',
                                'Services de transport')
