isced_formats_nl_nl <- c(
    '{{isced_broad_field}}',
    '{{isced_narrow_field}}',
    '{{isced_detailed_field}}'
)

isced_broad_field_nl_nl <- c("Algemene programma's en kwalificaties",
                             "Onderwijs / pedagogische wetenschappen",
                             "Kunst en letteren",
                             "Sociale wetenschappen, journalistiek en informatie",
                             "Handel, administratie en recht",
                             "Natuurwetenschappen, wiskunde en statistiek",
                             "Computerwetenschappen",
                             "Ingenieurswetenschappen, verwerkende industrie en bouw",
                             "Landbouw, bosbouw, visserij en diergeneeskunde",
                             "Gezondheid en sociale dienstverlening",
                             "Diensten")

isced_narrow_field_nl_nl <- c("Basisprogramma's en -kwalificaties",
                              "Geletterdheid en gecijferdheid",
                              "Persoonlijke vaardigheden en ontwikkeling",
                              "Onderwijs / pedagogische wetenschappen",
                              "Kunst",
                              "Letteren (behalve vreemde talen)",
                              "Vreemde talen",
                              "Sociale en gedragswetenschappen",
                              "Journalistiek en informatie",
                              "Handel en administratie",
                              "Recht",
                              "Biologie en aanverwante wetenschappen",
                              "Milieubescherming",
                              "Natuurwetenschappen",
                              "Wiskunde en statistiek",
                              "Computerwetenschappen",
                              "Ingenieurswetenschappen en aanverwante technieken",
                              "Produktie en produktieprocessen",
                              "Architectuur en bouw",
                              "Landbouw",
                              "Bosbouw",
                              "Visserij",
                              "Diergeneeskunde",
                              "Gezondheid",
                              "Welzijn",
                              "Persoonsdiensten",
                              "Gezondheid en hygi\xebne op het werk",
                              "Beveiliging",
                              "Transport")

isced_detailed_field_nl_nl <- c("Basisprogramma's en -kwalificaties",
                                "Geletterdheid en rekenvaardigheid",
                                "Persoonlijke vaardigheden en ontwikkeling",
                                "Pedagogische wetenschappen",
                                "Opleiding van leerkrachten voor het voorschools onderwijs",
                                "Lerarenopleiding /zonder specialisatie, niet gericht op een bepaalde discipline",
                                "Lerarenopleiding in bepaalde disciplines",
                                "Audio-visuele technieken en mediaproductie",
                                "Mode, binnenhuisinrichting en industri\xeble vormgeving",
                                "Schone Kunsten",
                                "Ambachten",
                                "Muziek en podiumkunsten",
                                "Religie en theologie",
                                "Geschiedenis en archeologie",
                                "Filosofie en ethiek",
                                "Taalverwerving",
                                "Literatuur en taalkunde",
                                "Economische wetenschappen",
                                "Politieke wetenschappen en maatschappijleer",
                                "Psychologie",
                                "Sociologie en cultuurwetenschappen",
                                "Journalistiek en verslaggeving",
                                "Bibliotheekwetenschappen, informatie en archivering",
                                "Accounting en fiscaliteit",
                                "Financi\xebn, bankwezen en verzekeringen",
                                "Management en administratie",
                                "Marketing en reclame",
                                "Secretariaats- en bureauwerk",
                                "Groothandel en kleinhandel",
                                "Werkgerelateerde vaardigheden",
                                "Recht",
                                "Biologie",
                                "Biochemie",
                                "Milieuwetenschappen",
                                "Natuurlijke leefomgevingen en wildleven",
                                "Scheikunde",
                                "Aardwetenschappen",
                                "Fysica",
                                "Wiskunde",
                                "Statistiek",
                                "Computergebruik",
                                "Ontwerp en beheer van databanken en netwerken",
                                "Ontwerpen en analyse van software en applicaties",
                                "Scheikundige processen",
                                "Milieubeschermingstechnologie",
                                "Electriciteit en energie",
                                "Elektronica en automatisatie",
                                "Mechanica en metaalbewerking",
                                "Motorvoertuigen, scheeps- en vliegtuigbouw",
                                "Voedselverwerking",
                                "Materialen (hout, papier, plastiek, glas)",
                                "Textiel, kleding, schoeisel en leder",
                                "Mijnkunde en grondstofwinning",
                                "Architectuur en stedebouw",
                                "Bouwkunde en civiele techniek",
                                "Landbouw en veeteelt",
                                "Tuinbouw",
                                "Bosbouw",
                                "Visserij",
                                "Diergeneeskunde",
                                "Tandheelkundige studies",
                                "Geneeskunde",
                                "Verpleegkunde en vroedkunde",
                                "Technieken in medische diagnostiek en behandeling",
                                "Therapie en revalidatie",
                                "Farmacie",
                                "Traditionele en aanvullende geneeskunde en therapie",
                                "Bejaarden- en gehandicaptenzorg",
                                "Kinderopvang en jeugddiensten",
                                "Maatschappelijk werk en begeleiding",
                                "Diensten aan huis",
                                "Haar-en schoonheidsverzorging",
                                "Hotel, restaurant en catering",
                                "Sport",
                                "Reizen, toerisme en vrije tijd",
                                "Volksgezondheid",
                                "Gezondheid en veiligheid op het werk",
                                "Leger en landsverdediging",
                                "Bescherming van personen en eigendommen",
                                "Transportdiensten")

